package ui

import "fmt"

// PrintUsage displays the main help text with ASCII art and command overview
func PrintUsage() {
	fmt.Println("     ")
	fmt.Println("██   ██  ▀▀█▄ ████▄ ████▄")
	fmt.Println("██ █ ██ ▄█▀██ ██ ▀▀ ██ ██")
	fmt.Println(" ██▀██  ▀█▄██ ██    ████▀")
	fmt.Println("                    ██    ")
	fmt.Println("                    ▀▀    ")
	fmt.Println(C.Dim + "a quick file and text transfer with SHA256 verification" + C.Reset)
	fmt.Println()

	fmt.Println(C.Bold + "Usage:" + C.Reset)
	fmt.Println("  " + C.Green + "warp send" + C.Reset + " [flags] <path>")
	fmt.Println("  " + C.Green + "warp send" + C.Reset + " --text <text>")
	fmt.Println("  " + C.Green + "warp send" + C.Reset + " --stdin < file")
	fmt.Println("  " + C.Green + "warp host" + C.Reset + " [flags]")
	fmt.Println("  " + C.Green + "warp receive" + C.Reset + " [flags] <url>")
	fmt.Println("  " + C.Green + "warp receive" + C.Reset + " --code <code>")
	fmt.Println("  " + C.Green + "warp search" + C.Reset + " [flags]")
	fmt.Println("  " + C.Green + "warp speedtest" + C.Reset + " [flags] <host>")
	fmt.Println("  " + C.Green + "warp config" + C.Reset + " [show|edit|path]")
	fmt.Println("  " + C.Green + "warp completion" + C.Reset + " [bash|zsh|fish|powershell]")
	fmt.Println()

	fmt.Println(C.Bold + "Commands:" + C.Reset)
	fmt.Println("  " + C.Magenta + "send" + C.Reset + "  Share a file, directory, or text snippet")
	fmt.Println("\t" + C.Yellow + "-p, --port" + C.Reset + "        choose specific port (default random)")
	fmt.Println("\t" + C.Yellow + "-i, --interface" + C.Reset + "   bind to a specific network interface")
	fmt.Println("\t" + C.Yellow + "--text string" + C.Reset + "     send a text snippet instead of a file")
	fmt.Println("\t" + C.Yellow + "--stdin" + C.Reset + "           read text from stdin")
	fmt.Println("\t" + C.Yellow + "--rate-limit" + C.Reset + "      limit bandwidth in Mbps (e.g., 10)")
	fmt.Println("\t" + C.Yellow + "--cache-size" + C.Reset + "      file cache size in MB (default 100)")
	fmt.Println("\t" + C.Yellow + "--no-qr" + C.Reset + "           skip printing the QR code")
	fmt.Println()
	fmt.Println("  " + C.Magenta + "host" + C.Reset + "  Receive uploads into a directory you control")
	fmt.Println("\t" + C.Yellow + "-i, --interface" + C.Reset + "   bind to a specific network interface")
	fmt.Println("\t" + C.Yellow + "-d, --dest" + C.Reset + "        destination directory for uploads (default .)")
	fmt.Println("\t" + C.Yellow + "--rate-limit" + C.Reset + "      limit bandwidth in Mbps (e.g., 10)")
	fmt.Println("\t" + C.Yellow + "--no-qr" + C.Reset + "           skip printing the QR code")
	fmt.Println()
	fmt.Println("  " + C.Magenta + "receive" + C.Reset + "  Download from a warp URL or PAKE code")
	fmt.Println("\t" + C.Yellow + "-c, --code" + C.Reset + "        PAKE code for secure transfer")
	fmt.Println("\t" + C.Yellow + "-o, --output" + C.Reset + "      write to a specific file or directory")
	fmt.Println("\t" + C.Yellow + "-f, --force" + C.Reset + "       overwrite existing files")
	fmt.Println("\t" + C.Yellow + "--workers" + C.Reset + "         parallel upload workers (default 3)")
	fmt.Println("\t" + C.Yellow + "--chunk-size" + C.Reset + "      chunk size in MB (default 2)")
	fmt.Println("\t" + C.Yellow + "--no-checksum" + C.Reset + "     skip SHA256 verification")
	fmt.Println("\t" + C.Yellow + "--from-clipboard" + C.Reset + "  scan QR code from clipboard")
	fmt.Println()
	fmt.Println("  " + C.Magenta + "search" + C.Reset + "   Discover nearby warp hosts via mDNS")
	fmt.Println("\t" + C.Yellow + "--timeout" + C.Reset + "          duration to wait for discovery (default 3s)")
	fmt.Println()
	fmt.Println("  " + C.Magenta + "speedtest" + C.Reset + "   Test network speed to a target host")
	fmt.Println("\t" + C.Yellow + "--timeout" + C.Reset + "          timeout for speed test (default 30s)")
	fmt.Println()
	fmt.Println("  " + C.Magenta + "config" + C.Reset + "   Manage configuration file")
	fmt.Println("\t" + C.Yellow + "init" + C.Reset + "              create config interactively")
	fmt.Println("\t" + C.Yellow + "show" + C.Reset + "              display current configuration")
	fmt.Println("\t" + C.Yellow + "edit" + C.Reset + "              open config file in $EDITOR")
	fmt.Println("\t" + C.Yellow + "path" + C.Reset + "              show config file path")
	fmt.Println()
	fmt.Println("  " + C.Magenta + "completion" + C.Reset + "   Generate shell completion scripts")
	fmt.Println("\t" + C.Yellow + "bash" + C.Reset + "              generate bash completion")
	fmt.Println("\t" + C.Yellow + "zsh" + C.Reset + "               generate zsh completion")
	fmt.Println("\t" + C.Yellow + "fish" + C.Reset + "              generate fish completion")
	fmt.Println("\t" + C.Yellow + "powershell" + C.Reset + "        generate powershell completion")
	fmt.Println()

	fmt.Println(C.Bold + "Examples:" + C.Reset)
	fmt.Println("  " + C.Green + "warp send" + C.Reset + " ./photo.jpg " + C.Dim + "		    # Share a file" + C.Reset)
	fmt.Println("  " + C.Green + "warp send" + C.Reset + " --text \"hello\" " + C.Dim + "	            # Share text" + C.Reset)
	fmt.Println("  " + C.Green + "warp host" + C.Reset + " -d uploads " + C.Dim + "		            # Save uploads to dir" + C.Reset)
	fmt.Println("  " + C.Green + "warp search" + C.Reset + " " + C.Dim + "				    # Discover hosts" + C.Reset)
	fmt.Println("  " + C.Green + "warp speedtest" + C.Reset + " 192.168.1.100 " + C.Dim + "             # Test network speed" + C.Reset)
	fmt.Println("  " + C.Green + "warp receive" + C.Reset + " --code 7-apple-velocity " + C.Dim + "     # Secure transfer" + C.Reset)
	fmt.Println("  " + C.Green + "warp receive" + C.Reset + " http://hostname:port/<token> " + C.Dim + "# Download" + C.Reset)
	fmt.Println()
	fmt.Println(C.Dim + "Use \"warp <command> -h\" for command-specific help." + C.Reset)
}
